"""
AutoBug AI — Report Service
==============================
Renders Markdown/HTML/JSON reports from agent pipeline state.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class ReportService:
    """Formats and exports AutoBug pipeline reports in multiple formats."""

    def to_markdown(self, report_str: str) -> str:
        """Return the Markdown report string (already generated by report_agent)."""
        return report_str

    def to_json(self, state: dict[str, Any]) -> dict[str, Any]:
        """Export a structured JSON report from pipeline state."""
        return {
            "issue_id": state.get("issue_id"),
            "repo_url": state.get("repo_url"),
            "root_cause": state.get("root_cause", {}),
            "patch": {
                "unified_diff": state.get("patch", {}).get("unified_diff", ""),
                "modified_files": state.get("patch", {}).get("modified_files", []),
                "summary": state.get("patch", {}).get("patch_summary", ""),
            },
            "validation": state.get("validation_result", {}),
            "pr_url": state.get("pr_url"),
            "agents_completed": state.get("steps_completed", []),
            "report_markdown": state.get("report", ""),
        }

    def to_html(self, report_str: str) -> str:
        """Convert Markdown report to HTML."""
        try:
            import markdown
            return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>AutoBug AI Report</title>
  <style>
    body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; }}
    pre {{ background: #1e1e1e; color: #d4d4d4; padding: 1rem; border-radius: 8px; overflow: auto; }}
    code {{ background: #f3f4f6; padding: 2px 6px; border-radius: 4px; }}
    table {{ border-collapse: collapse; width: 100%; }}
    td, th {{ border: 1px solid #e5e7eb; padding: 0.5rem 1rem; }}
    th {{ background: #f9fafb; }}
  </style>
</head>
<body>
{markdown.markdown(report_str, extensions=["tables", "fenced_code", "codehilite"])}
</body>
</html>"""
        except ImportError:
            return f"<pre>{report_str}</pre>"
