"""
AutoBug AI — Git Agent
========================
Creates a branch, applies the patch and commits the fix + tests.
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path

from app.agents.state import AutoBugState

logger = logging.getLogger(__name__)


async def git_agent(state: AutoBugState) -> AutoBugState:
    """Create branch, apply patch, commit changes."""
    logger.info("[GitAgent] Creating branch and committing patch")
    try:
        decision = state.get("decision") or {}
        if not decision.get("allow_commit", False):
            logger.warning("[GitAgent] Skipping commit: decision gate did not grant permission")
            return {**state, "steps_skipped": [*(state.get("steps_skipped") or []), "git_agent"]}
        import asyncio
        repo_path = state.get("repo_path", "")
        patch = state.get("patch") or {}
        tests = state.get("generated_tests") or {}
        root_cause = state.get("root_cause") or {}
        issue_id = state.get("issue_id", "unknown")

        if not repo_path:
            raise ValueError("repo_path not set in state")

        unified_diff = patch.get("unified_diff", "")
        if not unified_diff:
            return {
                **state,
                "branch_name": "",
                "commit_sha": "",
                "steps_completed": [*(state.get("steps_completed") or []), "git_agent"],
            }

        # Branch name
        error_slug = re.sub(r"[^a-z0-9]+", "-", root_cause.get("summary", "bugfix").lower())[:40]
        branch_name = f"autobug/{issue_id[:8]}-{error_slug}"

        def _git_ops() -> str:
            import git as gitpkg
            repo = gitpkg.Repo(repo_path)

            # Create and checkout branch
            branch = repo.create_head(branch_name, repo.head.commit)
            branch.checkout()

            # Apply patch
            patch_file = Path(repo_path) / ".autobug_fix.patch"
            patch_file.write_text(unified_diff, encoding="utf-8")
            try:
                result = subprocess.run(
                    ["git", "apply", "--index", str(patch_file)],
                    cwd=repo_path, capture_output=True, text=True,
                )
                if result.returncode != 0:
                    # Try patch -p1 as fallback
                    subprocess.run(
                        ["patch", "-p1", "-i", str(patch_file)],
                        cwd=repo_path, capture_output=True,
                    )
            finally:
                patch_file.unlink(missing_ok=True)

            # Write test file
            test_code = tests.get("test_code", "")
            test_file = tests.get("test_file", "tests/test_regression.py")
            if test_code:
                test_path = Path(repo_path) / test_file
                test_path.parent.mkdir(parents=True, exist_ok=True)
                test_path.write_text(test_code, encoding="utf-8")
                repo.index.add([test_file])

            # Stage all changes
            repo.git.add("-A")

            # Commit
            summary = root_cause.get("summary", "Fix bug")
            commit_msg = f"fix: {summary}\n\nGenerated by AutoBug AI\nIssue ID: {issue_id}"
            commit = repo.index.commit(
                commit_msg,
                author=gitpkg.Actor("AutoBug AI", "autobug@noreply.github.com"),
            )
            return commit.hexsha

        loop = asyncio.get_event_loop()
        commit_sha = await loop.run_in_executor(None, _git_ops)

        logger.info("[GitAgent] Committed %s on branch %s", commit_sha[:8], branch_name)
        return {
            **state,
            "branch_name": branch_name,
            "commit_sha": commit_sha,
            "steps_completed": [*(state.get("steps_completed") or []), "git_agent"],
            "error": None,
        }
    except Exception as exc:
        logger.error("[GitAgent] Failed: %s", exc, exc_info=True)
        return {
            **state,
            "branch_name": "",
            "commit_sha": "",
            "steps_completed": [*(state.get("steps_completed") or []), "git_agent"],
        }
